### ISSUE TITLE
binary rpm is serial only

### ISSUE THREAD

**Issue by quantumsteve** [SpinWaveGenie/SpinWaveGenie#78]
The rpm package only supports serial operation. Perhaps TBB should be added as a dependency?

@peterfpeterson: Was this by design?

**Comment by peterfpeterson** [comment]
If you can detect it a runtime, then it can be added as an "optional" dependency. If it is a compile time thing, them it would have to be a hard requirement like you suggest. I think it was originally done to be a "minimal" package. The alternative is have an rpm with everything, or to figure out how to sub-packages, with the first one being `spinwavegenie-tbb`. I've never tried to make sub-packages, but it can't be that hard.
